<?php

namespace Tests\Feature;

use App\Http\Controllers\AdminAttendance\AttendanceLeaveController;
use App\Http\Controllers\AdminAttendance\AttendanceOvertimeController;
use App\Http\Controllers\AdminAttendance\AttendanceOverviewController;
use App\Http\Controllers\AdminAttendance\AttendanceRecapController;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;
use Tests\TestCase;

class AdminAttendanceOverviewStructureTest extends TestCase
{
    public function test_overview_and_recap_use_separate_controllers(): void
    {
        $overviewRoute = Route::getRoutes()->getByName('admin-attendance.overview');
        $recapRoute = Route::getRoutes()->getByName('admin-attendance.recap');
        $monthlyDatatableRoute = Route::getRoutes()->getByName('admin-attendance.recap.monthly-datatable');
        $detailRoute = Route::getRoutes()->getByName('admin-attendance.recap.detail-employees');
        $detailDatatableRoute = Route::getRoutes()->getByName('admin-attendance.recap.detail-employees.datatable');
        $leaveRoute = Route::getRoutes()->getByName('admin-attendance.leave');
        $leavePendingDatatableRoute = Route::getRoutes()->getByName('admin-attendance.leave.pending-datatable');
        $leaveApprovedDatatableRoute = Route::getRoutes()->getByName('admin-attendance.leave.approved-datatable');
        $leaveDetailRoute = Route::getRoutes()->getByName('admin-attendance.leave.detail');
        $businessTripRoute = Route::getRoutes()->getByName('admin-attendance.business-trip');
        $businessTripDetailRoute = Route::getRoutes()->getByName('admin-attendance.business-trip.detail');
        $overtimeRoute = Route::getRoutes()->getByName('admin-attendance.overtime');
        $overtimeDetailRoute = Route::getRoutes()->getByName('admin-attendance.overtime.detail');
        $overtimeApprovalRoute = Route::getRoutes()->getByName('admin-attendance.overtime.approval');
        $overviewView = File::get(resource_path('views/admin_attendance/overview/index.blade.php'));
        $overtimeDetailView = File::get(resource_path('views/admin_attendance/overtime/detail.blade.php'));
        $overviewController = File::get(app_path('Http/Controllers/AdminAttendance/AttendanceOverviewController.php'));
        $recapController = File::get(app_path('Http/Controllers/AdminAttendance/AttendanceRecapController.php'));
        $leaveController = File::get(app_path('Http/Controllers/AdminAttendance/AttendanceLeaveController.php'));
        $overtimeController = File::get(app_path('Http/Controllers/AdminAttendance/AttendanceOvertimeController.php'));

        $this->assertSame(AttendanceOverviewController::class.'@index', $overviewRoute?->getActionName());
        $this->assertSame(AttendanceRecapController::class.'@index', $recapRoute?->getActionName());
        $this->assertSame(AttendanceRecapController::class.'@monthlyDatatable', $monthlyDatatableRoute?->getActionName());
        $this->assertSame(AttendanceRecapController::class.'@employeeDetails', $detailRoute?->getActionName());
        $this->assertSame(AttendanceLeaveController::class.'@index', $leaveRoute?->getActionName());
        $this->assertSame(AttendanceLeaveController::class.'@pendingDatatable', $leavePendingDatatableRoute?->getActionName());
        $this->assertSame(AttendanceLeaveController::class.'@approvedDatatable', $leaveApprovedDatatableRoute?->getActionName());
        $this->assertSame(AttendanceLeaveController::class.'@detail', $leaveDetailRoute?->getActionName());
        $this->assertSame('admin-attendance/leave', $leaveRoute?->uri());
        $this->assertSame('admin-attendance/leave/pending-datatable', $leavePendingDatatableRoute?->uri());
        $this->assertSame('admin-attendance/leave/approved-datatable', $leaveApprovedDatatableRoute?->uri());
        $this->assertSame('admin-attendance/leave/detail/{uid}', $leaveDetailRoute?->uri());
        $this->assertSame('admin-attendance/business-trip', $businessTripRoute?->uri());
        $this->assertSame('admin-attendance/business-trip/detail', $businessTripDetailRoute?->uri());
        $this->assertSame('admin-attendance/overtime', $overtimeRoute?->uri());
        $this->assertSame('admin-attendance/overtime/detail/{uid}', $overtimeDetailRoute?->uri());
        $this->assertSame(AttendanceOvertimeController::class.'@updateApproval', $overtimeApprovalRoute?->getActionName());
        $this->assertSame('admin-attendance/overtime/detail/{uid}/approval', $overtimeApprovalRoute?->uri());
        $this->assertSame('admin-attendance/recap-attendance/datatable', $monthlyDatatableRoute?->uri());
        $this->assertSame(AttendanceRecapController::class.'@employeeDetailsDatatable', $detailDatatableRoute?->getActionName());
        $this->assertSame('admin-attendance/recap-attendance/{employee}', $detailRoute?->uri());
        $this->assertSame('admin-attendance/recap-attendance/{employee}/datatable', $detailDatatableRoute?->uri());
        $this->assertStringContainsString('overviewViewData', $overviewController);
        $this->assertStringContainsString('activeEmployeeIdsFor($dailyAttendanceDate)', $overviewController);
        $this->assertStringContainsString("->where('late_minutes', '<=', 0)->orderBy('clock_in')->limit(5)", $overviewController);
        $this->assertStringContainsString("->where('late_minutes', '>', 0)->orderByDesc('clock_in')->limit(5)", $overviewController);
        $this->assertStringContainsString("->whereDoesntHave('roles'", $overviewController);
        $this->assertStringContainsString("->where('name', 'superuser')", $overviewController);
        $this->assertStringContainsString("->whereNotIn('email', self::EXCLUDED_ATTENDANCE_DETAIL_EMAILS)", $overviewController);
        $this->assertStringContainsString("->whereRaw('LOWER(COALESCE(workplace, \"\")) <> ?', ['rnb jakarta'])", $overviewController);
        $this->assertStringNotContainsString('currentCompanyIdFor', $overviewController);
        $this->assertStringNotContainsString("->where('current_company_id', \$companyId)", $overviewController);
        $this->assertStringNotContainsString('function recap', $overviewController);
        $this->assertStringNotContainsString('AttendanceOverviewController', $recapController);
        $this->assertStringContainsString('recapViewData', $recapController);
        $this->assertStringContainsString('monthlyDatatable', $recapController);
        $this->assertStringContainsString('recapEmployeeDetailData', $recapController);
        $this->assertStringContainsString("'profile:id,employee_id,name,profile_picture_path'", $recapController);
        $this->assertStringContainsString("'avatar_url' => \$this->employeeAvatarUrl(\$employee->profile?->profile_picture_path)", $recapController);
        $this->assertStringContainsString("asset('assets/default_user.jpg')", $recapController);
        $this->assertStringContainsString('recapVirtualHolidayRows', $recapController);
        $this->assertStringContainsString('recapDaysLabel', $recapController);
        $this->assertStringContainsString('recapEmployeeWorkDays', $recapController);
        $this->assertStringContainsString('$holidayKeys = AttendanceHoliday::query()', $recapController);
        $this->assertStringContainsString('->reject(fn (Carbon $date): bool => $holidayKeys->has($date->toDateString()))', $recapController);
        $this->assertStringContainsString('employeeDetailsDatatable', $recapController);
        $this->assertStringContainsString('activeEmployeeIdsFor($now)', $recapController);
        $this->assertStringContainsString("->whereRaw('LOWER(COALESCE(workplace, \"\")) <> ?', ['rnb jakarta'])", $recapController);
        $this->assertStringNotContainsString("->where('current_company_id', \$companyId)", $recapController);
        $this->assertStringContainsString("'recapDetailMonth' => \$detailContext['month']", $recapController);
        $this->assertStringContainsString('recapAttendanceLogRows', $recapController);
        $this->assertStringContainsString('recapMonthlyRows', $recapController);
        $this->assertStringContainsString('$monthlyWorkingDaysCount = $this->recapWorkDaysBetween(', $recapController);
        $this->assertStringContainsString('$monthlyExpectedWorkMinutes = $monthlyWorkingDaysCount * 8 * 60;', $recapController);
        $this->assertStringContainsString("'working_days' => \$attendedDateKeys->count().' / '.\$monthlyWorkingDaysCount.' days',", $recapController);
        $this->assertStringContainsString('recapCompactMinutesLabel($monthlyExpectedWorkMinutes)', $recapController);
        $this->assertStringContainsString("private const TASK_HOURS_VERIFICATION = 'task_hours_verification';", $recapController);
        $this->assertStringContainsString("->whereNotNull('approved_start_time')", $recapController);
        $this->assertStringContainsString("->whereNotNull('approved_end_time')", $recapController);
        $this->assertStringContainsString("->where('event_key', self::TASK_HOURS_VERIFICATION)", $recapController);
        $this->assertStringContainsString('recapApprovedOvertimeMinutes', $recapController);
        $this->assertStringContainsString('$end->addDay();', $recapController);
        $this->assertStringNotContainsString("->get(['employee_id', 'overtime_date', 'calculated_hours'])", $recapController);
        $this->assertStringNotContainsString("->get(['calculated_hours'])", $recapController);
        $this->assertStringNotContainsString("'working_days' => \$attendedDateKeys->count().' / '.\$employeeWorkDays->count().' days'", $recapController);
        $this->assertStringContainsString("'leaveOverviewStats' => \$this->leaveOverviewStatsFor(\$request)", $leaveController);
        $this->assertStringContainsString("'leavePendingCards' => \$this->pendingLeaveCardsFor(\$request, \$selectedPeriod)", $leaveController);
        $this->assertStringContainsString("'leaveGridPositionGroups' => \$this->leaveGridPositionGroupsFor(\$request, \$selectedPeriod)", $leaveController);
        $this->assertStringContainsString('private function pendingLeaveCardsFor(Request $request, array $selectedPeriod): Collection', $leaveController);
        $this->assertStringContainsString('private function leaveGridPositionGroupsFor(Request $request, array $selectedPeriod): Collection', $leaveController);
        $this->assertStringContainsString('current_position_id', $leaveController);
        $this->assertStringContainsString('pendingDatatable', $leaveController);
        $this->assertStringContainsString('approvedDatatable', $leaveController);
        $this->assertStringContainsString('leaveRequestsDatatable', $leaveController);
        $this->assertStringContainsString('countSupervisorApprovedPendingLeaveRequests', $leaveController);
        $this->assertStringContainsString('applySupervisorApprovedReviewFilter', $leaveController);
        $this->assertStringContainsString("->whereHas('histories'", $leaveController);
        $this->assertStringContainsString("->where('event_type', 'supervisor_review')", $leaveController);
        $this->assertStringContainsString("->where('to_status', 'approved')", $leaveController);
        $this->assertStringContainsString("DB::table('employee_pic_assignments')", $leaveController);
        $this->assertStringContainsString("->where('staff_employee_id', \$staffEmployeeId)", $leaveController);
        $this->assertStringContainsString("->value('supervisor_employee_id')", $leaveController);
        $this->assertStringContainsString('leaveBalanceCardsFor', $leaveController);
        $this->assertStringContainsString('leaveTrackerFor', $leaveController);
        $this->assertStringContainsString('use App\Services\Leave\JointHolidaySummaryService;', $leaveController);
        $this->assertStringContainsString('private readonly JointHolidaySummaryService $jointHolidaySummaryService', $leaveController);
        $this->assertStringContainsString('$this->jointHolidaySummaryService->forYear($year, $today)', $leaveController);
        $this->assertStringContainsString('countLeaveRequestsBetween', $leaveController);
        $this->assertStringContainsString('countLeaveRequestsByType', $leaveController);
        $this->assertStringContainsString('supervisorApprovedLeaveRequestQuery', $leaveController);
        $this->assertStringContainsString('return (int) $this->supervisorApprovedLeaveRequestQuery($activeEmployeeIds)', $leaveController);
        $this->assertStringContainsString('current_company_id', $leaveController);
        $this->assertStringContainsString('$legacyMonth = $request->query(\'month\');', $overtimeController);
        $this->assertStringContainsString('$cardMonth = $this->normalizeMonth($request->query(\'card_month\', $legacyMonth));', $overtimeController);
        $this->assertStringContainsString('$request->query(\'pending_month\', $legacyMonth)', $overtimeController);
        $this->assertStringContainsString('$request->query(\'complete_month\', $legacyMonth)', $overtimeController);
        $this->assertStringContainsString('$metricBuilder->summarizeForPeriod(null, null, $cardMonth, $cardYear)', $overtimeController);
        $this->assertStringContainsString('$this->adminOvertimeCardsFor(null, $cardMonth, $cardYear)', $overtimeController);
        $this->assertStringContainsString("'selectedCardMonth' => \$cardMonth", $overtimeController);
        $this->assertStringContainsString("'selectedPendingMonth' => \$pendingTableData['selectedMonth']", $overtimeController);
        $this->assertStringContainsString("'selectedCompleteMonth' => \$completeTableData['selectedMonth']", $overtimeController);
        $this->assertStringContainsString("'approvedRows' => \$completeTableData['approvedRows']", $overtimeController);
        $this->assertStringContainsString('private function yearOptionsForFilters(mixed ...$selectedYearsAndOptions): array', $overtimeController);
        $this->assertStringContainsString("'staff_submitted_time_range' => \$actualTimeRange", $overtimeController);
        $this->assertStringContainsString("'staff_submitted_duration' => \$actualDuration", $overtimeController);
        $this->assertStringContainsString("'description' => (string) (\$projectTask->description ?? '')", $overtimeController);
        $this->assertStringContainsString("'status_value' => \$status !== '' ? \$status : 'pending'", $overtimeController);
        $this->assertStringContainsString("'date_range_label' => \$this->taskDateRangeLabel", $overtimeController);
        $this->assertStringContainsString("'status_label' => \$this->projectTaskDetailStatusLabel", $overtimeController);
        $this->assertStringContainsString("'task_category_label' => \$projectTask->project_id !== null ? 'Project Task' : 'Daily Task'", $overtimeController);
        $this->assertStringContainsString("'assigned_by' => trim((string) (\$projectTask->assignedBy?->username ?? 'self')) ?: 'self'", $overtimeController);
        $this->assertStringContainsString("'attachment_path' => (string) (\$projectTask->attachment_path ?? '')", $overtimeController);
        $this->assertStringContainsString('private function projectTaskDetailStatusLabel', $overtimeController);
        $this->assertStringContainsString('private function taskDateRangeLabel', $overtimeController);
        $this->assertStringContainsString('private function formatDateInputValue(mixed $dateValue): string', $overtimeController);
        $this->assertStringContainsString('$actualEndDateTime = $this->formatActualEndDateTime($overtime);', $overtimeController);
        $this->assertStringContainsString("'verified_datetime' => \$actualEndDateTime !== '-' ? \$actualEndDateTime : \$this->formatLifecycleDateTime(\$verificationLog)", $overtimeController);
        $this->assertStringContainsString('private function formatActualEndDateTime(AttendanceOvertime $overtime): string', $overtimeController);
        $this->assertStringContainsString('public function updateApproval(Request $request, string $uid): RedirectResponse', $overtimeController);
        $this->assertStringContainsString("'payroll_processing_status' => ['required', 'in:approved,rejected']", $overtimeController);
        $this->assertStringContainsString("\$payrollStatus = \$status === 'approved' ? 'calculated_locked' : 'rejected';", $overtimeController);
        $this->assertStringContainsString("'director_approval',", $overtimeController);
        $this->assertStringContainsString("'payroll_processing_approval_status' => match (\$payrollStatus)", $overtimeController);
        $this->assertStringContainsString("'can_update_payroll_processing' => \$payrollStatus === 'pending'", $overtimeController);
        $this->assertStringContainsString('$showActualTime = $this->hasApprovedOvertimeTimes($overtime) || $this->hasActualOvertimeTimes($overtime);', $overtimeController);
        $this->assertStringContainsString("'time_lines' => \$this->timeLinesFor(\$overtime, \$showActualTime)", $overtimeController);
        $this->assertStringContainsString("'director_approval_status' => in_array(\$directorStatus, ['pending', 'approved', 'rejected'], true) ? \$directorStatus : 'pending'", $overtimeController);
        $this->assertStringContainsString("'can_update_director_approval' => \$directorStatus === 'pending'", $overtimeController);
        $this->assertStringNotContainsString('$this->currentCompanyIdFor($authenticatedUser)', $overtimeController);
        $this->assertStringContainsString('private function resolveOvertimeDirectorApprover(AttendanceOvertime $overtime): ?User', $overtimeController);
        $this->assertStringContainsString("->whereRaw('LOWER(email) = ?', ['lukman@rnbmanagement.com'])", $overtimeController);
        $this->assertStringContainsString("->orWhereHas('employee.deployment.position'", $overtimeController);
        $this->assertStringContainsString("->orWhereHas('employee.deployment.positions'", $overtimeController);
        $this->assertStringNotContainsString("['label' => \$plannedTimeLabel, 'strike' => true]", $overtimeController);
        $this->assertStringNotContainsString('$companyId = $overtime->employee?->deployment?->current_company_id;', $overtimeController);
        $this->assertStringContainsString('Staff Start ClockIn', $overtimeDetailView);
        $this->assertStringContainsString('Staff Start ClockOut', $overtimeDetailView);
        $this->assertStringContainsString('$overtimeDetail[\'actual_start_time\']', $overtimeDetailView);
        $this->assertStringContainsString('$overtimeDetail[\'actual_end_time\']', $overtimeDetailView);
        $this->assertStringContainsString('$overtimeDetail[\'actual_time_range\']', $overtimeDetailView);
        $this->assertStringContainsString('$overtimeDetail[\'approved_time_range\']', $overtimeDetailView);
        $this->assertStringContainsString('$overtimeDetail[\'actual_duration\']', $overtimeDetailView);
        $this->assertStringContainsString('$overtimeDetail[\'approved_duration\']', $overtimeDetailView);
        $this->assertStringNotContainsString('Staff submitted <span class="text-muted">(Total Duration)</span>', $overtimeDetailView);
        $this->assertStringNotContainsString('Scheduled Start', $overtimeDetailView);
        $this->assertStringNotContainsString('Scheduled End', $overtimeDetailView);
        $this->assertStringNotContainsString('$overtimeDetail[\'planned_time_range\']', $overtimeDetailView);
        $this->assertStringNotContainsString('$overtimeDetail[\'planned_duration\']', $overtimeDetailView);
        $this->assertStringContainsString('<span class="text-gray fw-semibold text-decoration-line-through">-</span>', $overtimeDetailView);
        $this->assertStringContainsString('$taskItemPayload = $taskItems->keyBy(\'id\')->toArray();', $overtimeDetailView);
        $this->assertStringContainsString('admin-overtime-task-detail', $overtimeDetailView);
        $this->assertStringContainsString('id="adminTaskDetailModal"', $overtimeDetailView);
        $this->assertStringContainsString('Task Details', $overtimeDetailView);
        $this->assertStringContainsString('id="adminTaskDetailCategory"', $overtimeDetailView);
        $this->assertStringContainsString('id="adminTaskDetailProject"', $overtimeDetailView);
        $this->assertStringContainsString('id="adminTaskDetailAssignedBy"', $overtimeDetailView);
        $this->assertStringContainsString('var taskItemsById = @js($taskItemPayload ?? []);', $overtimeDetailView);
        $this->assertStringContainsString("$('#adminTaskDetailTitle').text(nullableTaskText(taskItem.title));", $overtimeDetailView);
        $this->assertStringContainsString("$('#adminTaskDetailBlockers').text(nullableTaskText(taskItem.blockers));", $overtimeDetailView);
        $this->assertStringContainsString("$('#adminTaskDetailAssignedBy').text('@' + (nullableTaskValue(taskItem.assigned_by) || 'self'));", $overtimeDetailView);
        $this->assertStringContainsString("renderTaskAttachment('#adminTaskDetailAttachment', taskItem.attachment_path);", $overtimeDetailView);
        $this->assertStringContainsString("route('admin-attendance.overtime.approval'", $overtimeDetailView);
        $this->assertStringContainsString('<h4 class="card-title">Confirm Overtime</h4>', $overtimeDetailView);
        $this->assertStringContainsString('$payrollProcessingApprovalStatus', $overtimeDetailView);
        $this->assertStringContainsString('$canUpdatePayrollProcessing', $overtimeDetailView);
        $this->assertStringContainsString('name="payroll_processing_status"', $overtimeDetailView);
        $this->assertStringContainsString('value="approved"', $overtimeDetailView);
        $this->assertStringContainsString('value="rejected"', $overtimeDetailView);
        $this->assertStringContainsString("'adminOvertimeApproval'", $overtimeDetailView);
        $this->assertStringContainsString('<span class="text-gray">, {{ $overtimeDetail[\'approved_time_range\'] ?? \'-\' }}</span>', $overtimeDetailView);
        $this->assertStringContainsString('<span class="text-gray">, {{ $overtimeDetail[\'approved_duration\'] ?? \'-\' }}</span>', $overtimeDetailView);
        $this->assertStringNotContainsString('Rp. 100.000', $overtimeDetailView);
        $this->assertStringContainsString('<span class="fs-12 text-black">Alpha</span>', $overviewView);
        $this->assertStringContainsString('fa-solid fa-user-check text-success', $overviewView);
        $this->assertStringContainsString('fa-solid fa-user-clock text-danger', $overviewView);
        $this->assertStringContainsString('fa-solid fa-user-xmark text-warning', $overviewView);
        $this->assertStringContainsString('fa-solid fa-calendar-minus text-info', $overviewView);
        $this->assertStringContainsString('.admin-attendance-metric-icon svg', $overviewView);
        $this->assertStringContainsString('Alpha ({{ $dailyDeviationPercent }}%)', $overviewView);
        $this->assertStringContainsString('"fill": ["var(--bs-warning)", "var(--bs-light)"]', $overviewView);
        $this->assertStringContainsString("['#2BC155', '#F94687', '#1EA7C5', '#FFBC11']", $overviewView);
        $this->assertStringNotContainsString('<span class="fs-12 text-black">Deviation</span>', $overviewView);
        $this->assertStringNotContainsString('Deviation ({{ $dailyDeviationPercent }}%)', $overviewView);
        $this->assertTrue(View::exists('admin_attendance.overview.index'));
        $this->assertTrue(View::exists('admin_attendance.recap_attendance.index'));
        $this->assertTrue(View::exists('admin_attendance.recap_attendance.detail-employees'));
        $this->assertTrue(View::exists('admin_attendance.leave.index'));
        $this->assertTrue(View::exists('admin_attendance.leave.detail'));
        $this->assertTrue(View::exists('admin_attendance.business_trip.index'));
        $this->assertTrue(View::exists('admin_attendance.business_trip.detail'));
        $this->assertTrue(View::exists('admin_attendance.overtime.index'));
        $this->assertTrue(View::exists('admin_attendance.overtime.detail'));
    }

    public function test_admin_attendance_navigation_links_to_overview_and_recap(): void
    {
        $navbar = File::get(resource_path('views/admin_attendance/layout/navbar.blade.php'));
        $sidebar = File::get(resource_path('views/layouts/sidebar.blade.php'));

        $this->assertStringContainsString("route('admin-attendance.overview')", $navbar);
        $this->assertStringContainsString("route('admin-attendance.recap')", $navbar);
        $this->assertStringContainsString("request()->routeIs('admin-attendance.recap*')", $navbar);
        $this->assertStringContainsString("route('admin-attendance.leave')", $navbar);
        $this->assertStringContainsString("request()->routeIs('admin-attendance.leave*')", $navbar);
        $this->assertStringContainsString("route('admin-attendance.business-trip')", $navbar);
        $this->assertStringContainsString("request()->routeIs('admin-attendance.business-trip*')", $navbar);
        $this->assertStringContainsString("route('admin-attendance.overtime')", $navbar);
        $this->assertStringContainsString("request()->routeIs('admin-attendance.overtime*')", $navbar);
        $this->assertStringContainsString("route('admin-attendance.overview')", $sidebar);
    }

    public function test_recap_views_keep_dynamic_data_bindings(): void
    {
        $recapView = File::get(resource_path('views/admin_attendance/recap_attendance/index.blade.php'));
        $detailView = File::get(resource_path('views/admin_attendance/recap_attendance/detail-employees.blade.php'));
        $leaveIndexView = File::get(resource_path('views/admin_attendance/leave/index.blade.php'));
        $leaveController = File::get(app_path('Http/Controllers/AdminAttendance/AttendanceLeaveController.php'));

        $this->assertStringContainsString('@forelse ($recapAttendanceLogRows as $row)', $recapView);
        $this->assertStringContainsString('id="recapAttendanceCaptureButton"', $recapView);
        $this->assertStringContainsString('id="recapAttendanceCaptureArea"', $recapView);
        $this->assertStringContainsString('id="recapAttendanceCaptureTable"', $recapView);
        $this->assertStringContainsString('<th>Address</th>', $recapView);
        $this->assertStringContainsString("<td>{{ \$row['location_address'] }}</td>", $recapView);
        $this->assertStringContainsString('var columnWidths = [240, 130, 130, 260, 360, 160, 120];', $recapView);
        $this->assertStringNotContainsString('<h4 class="card-title m-0">Attendance Logs ({{ $recapAttendanceDateLabel }})</h4>', $recapView);
        $this->assertStringContainsString('function downloadRecapAttendanceImage()', $recapView);
        $this->assertStringContainsString('data-capture-tone="{{ $row[\'attachment_badge\'] }}"', $recapView);
        $this->assertStringContainsString('function captureToneFromElement(element)', $recapView);
        $this->assertStringContainsString('function captureTonePalette(tone)', $recapView);
        $this->assertStringContainsString('drawCaptureBadge(context, lines[0], palette', $recapView);
        $this->assertStringContainsString("link.download = filename + '.png';", $recapView);
        $this->assertStringContainsString('id="recapMonthlyTable"', $recapView);
        $this->assertStringContainsString('admin-attendance.recap.monthly-datatable', $recapView);
        $this->assertStringContainsString('employeeDetailBaseUrl', $recapView);
        $this->assertStringContainsString('monthlyTable.ajax.reload()', $recapView);
        $this->assertStringContainsString('Attendance Recap', $detailView);
        $this->assertStringContainsString("recapDetailEmployee['employee_code']", $detailView);
        $this->assertStringContainsString("recapDetailEmployee['id']", $detailView);
        $this->assertStringContainsString('admin-attendance-detail-info', $detailView);
        $this->assertStringContainsString('admin-attendance-detail-info-value', $detailView);
        $this->assertStringNotContainsString('<span>{{ $recapDetailEmployee[\'employee_code\'] ?? \'-\' }}</span> <br>', $detailView);
        $this->assertStringContainsString('col-md-3 mb-3 mb-md-0', $detailView);
        $this->assertStringContainsString('id="recapDetailPeriodFilter"', $detailView);
        $this->assertStringContainsString('id="recapDetailMonthFilter"', $detailView);
        $this->assertStringContainsString('id="recapDetailYearFilter"', $detailView);
        $this->assertStringContainsString("detailMonthFilter.addEventListener('change', reloadDetailTable)", $detailView);
        $this->assertStringContainsString('admin-attendance.recap.detail-employees.datatable', $detailView);
        $this->assertStringContainsString('detailTable.ajax.reload()', $detailView);
        $this->assertStringNotContainsString('history.replaceState', $detailView);
        $this->assertStringContainsString('id="recapDetailAttendanceTable"', $detailView);
        $this->assertStringContainsString('<th class="mw-160">Address</th>', $detailView);
        $this->assertStringContainsString("{ data: 'location_address', render: function(data) { return escapeHtml(data); } }", $detailView);
        $this->assertStringNotContainsString("$('#tableLicenseUsage').DataTable", $detailView);
        $this->assertStringNotContainsString('scrollX: true', $detailView);
        $this->assertStringContainsString('admin-attendance-detail-avatar', $detailView);
        $this->assertStringContainsString('assets/vendor/apexcharts/dist/apexcharts.min.js', $detailView);
        $this->assertStringContainsString("typeof ApexCharts === 'undefined'", $detailView);
        $this->assertStringContainsString('if (!$.fn.peity)', $detailView);
        $this->assertStringNotContainsString('admin-attendance-person-avatar', $detailView);
        $this->assertStringNotContainsString('admin-attendance-empty', $detailView);
        $this->assertStringNotContainsString('attendance-rate-mobile-slider', $detailView);
        $this->assertStringNotContainsString('admin-attendance-overview-card', $detailView);
        $this->assertStringContainsString("\$leaveOverviewStats['pending']", $leaveIndexView);
        $this->assertStringContainsString('@forelse ($leavePendingCards as $leavePendingCard)', $leaveIndexView);
        $this->assertStringContainsString('id="adminLeavePendingTable"', $leaveIndexView);
        $this->assertStringContainsString('id="adminLeaveApprovedTable"', $leaveIndexView);
        $this->assertStringContainsString('admin-attendance.leave.pending-datatable', $leaveIndexView);
        $this->assertStringContainsString('admin-attendance.leave.approved-datatable', $leaveIndexView);
        $this->assertStringContainsString('table.ajax.reload()', $leaveIndexView);
        $leaveDetailView = File::get(resource_path('views/admin_attendance/leave/detail.blade.php'));
        $this->assertStringContainsString("\$leaveEligibility['available_balance_label']", $leaveDetailView);
        $this->assertStringContainsString("\$leaveEligibility['joint_holiday_label']", $leaveDetailView);
        $this->assertStringContainsString("\$leaveEligibility['supervisor_name']", $leaveDetailView);
        $this->assertStringContainsString("\$leaveEligibility['next_accrual_label']", $leaveDetailView);
        $this->assertStringContainsString("\$leaveTracker['annual_leave_taken_label']", $leaveDetailView);
        $this->assertStringContainsString("\$leaveTracker['annual_leave_taken_month_label']", $leaveDetailView);
        $this->assertStringContainsString("\$leaveTracker['pending_requests_label']", $leaveDetailView);
        $this->assertStringContainsString("\$leaveTracker['unpaid_leave_taken_label']", $leaveDetailView);
        $this->assertStringContainsString('card leave-summary-card mb-5', $leaveDetailView);
        $this->assertStringContainsString('leave-summary-icon--eligibility', $leaveDetailView);
        $this->assertStringContainsString('leave-summary-icon--tracker', $leaveDetailView);
        $this->assertStringContainsString('href="#Eligibility"', $leaveDetailView);
        $this->assertStringContainsString('href="#Tracker"', $leaveDetailView);
        $this->assertStringContainsString('id="Eligibility"', $leaveDetailView);
        $this->assertStringContainsString('id="Tracker"', $leaveDetailView);
        $this->assertStringNotContainsString('href="#Running"', $leaveDetailView);
        $this->assertStringNotContainsString('href="#Cycling"', $leaveDetailView);
        $this->assertStringContainsString("\$leaveApproval['special_leave_type_label']", $leaveDetailView);
        $this->assertStringContainsString("\$leaveApproval['attachment_url']", $leaveDetailView);
        $this->assertStringContainsString('admin-attendance.leave.approval.update', $leaveDetailView);
        $this->assertStringContainsString('w-100 btn-lg', $leaveDetailView);
        $this->assertStringContainsString('leaveApprovalFor', $leaveController);
        $this->assertStringContainsString("->where('event_type', 'hr_verification')", $leaveController);
        $this->assertStringContainsString("->where('to_status', 'pending')", $leaveController);
        $this->assertStringContainsString("'event_type' => 'status_updated'", $leaveController);
        $this->assertStringNotContainsString('Tidak dapat menyetujui pengajuan cuti milik sendiri.', $leaveController);
        $this->assertStringContainsString("default => 'text-warning',", $leaveController);
        $leaveRequestHistoryModel = File::get(app_path('Models/LeaveRequestHistory.php'));
        $this->assertStringContainsString("'title' => 'HR Verification (Pending)'", $leaveRequestHistoryModel);
        $this->assertStringContainsString('isApprovedSupervisorReview', $leaveRequestHistoryModel);
        $this->assertStringContainsString('id="project-grid-tab"', $leaveIndexView);
        $this->assertStringContainsString('id="project-grid-pane"', $leaveIndexView);
        $this->assertStringContainsString("setLeaveView('grid')", $leaveIndexView);
        $this->assertStringContainsString('@forelse ($leaveGridPositionGroups as $positionIndex => $positionGroup)', $leaveIndexView);
        $this->assertStringContainsString("{{ \$positionGroup['position_name'] }}", $leaveIndexView);
        $this->assertStringContainsString("@foreach (\$positionGroup['employees'] as \$gridEmployee)", $leaveIndexView);
    }
}
